### ISSUE TITLE
Command /me + Auto complétion

### ISSUE THREAD

**Issue by hardware** [mondediefr/mondedie-chat#10]
Note: Faire en sorte de cacher les commandes pour les utilisateurs

Liste des commandes à rajouter:
- [ ] `/kick @user` seulement modérateur
- [ ] `/unban @user` seulement modérateur
- [ ] `/ban list` seulement modérateur
- [ ] `/unlock @user` seulement modérateur
- [ ] `/me` à tous

**Comment by soyuka** [comment]
duplicate #11 
duplicate #2

**Comment by Hydrog3n** [comment]
Le unlock c'est quoi en fait ?

**Comment by hardware** [comment]
ça permet de débloquer un utilisateur qui serait resté dans la liste des utilisateurs connectés après la fermeture du socket. ça arrive quasiment jamais, mais imagine qu'un utilisateur se déconnecte en même temps qu'on push une modif sur l'instance, Redis étant pas disponible, le socket va se fermer mais l'utilisateur restera dans la bdd.

Donc ça pourra toujours servir ^^

**Comment by Hydrog3n** [comment]
Ah super je savais pas.

**Comment by hardware** [comment]
Je clos aussi cette issue, ajouter l'auto-complétion des commandes de modération n'est pas très utile, on les utilise pas tous les jours et on les connait ^^ 

En plus ça va alourdir le système d'auto-complétion en ajoutant la vérification des droits de modération.

**Comment by al3xLvs** [comment]
ok
