### ISSUE TITLE
Dédoublement de la liste des utilisateurs connectés

### ISSUE THREAD

**Issue by hardware** [mondediefr/mondedie-chat#18]
Parfois la liste des utilisateurs connectés apparaît en double (voir plus). Je pense que ça vient du fait que le listener sur l'événement **user_connected** est enregistré une deuxième fois pour une raison que je ne maîtrise pas (problème réseau, déco/reco du chat suite à un push...etc).

``` javascript
socket.on('user_connected', function(user) {
    vm.list.push(new users.User(user));
    m.redraw();
});
```

Je viens d'en avoir un à l'instant :

![screen](https://i.gyazo.com/da2365d580b0db0ddb13dbfbf7d04a26.png)
![screen](https://i.gyazo.com/5ffad32e32bcf87011215bef83326302.png)

```
2015-12-06T09:42:39 heroku router - - at=error code=H13 desc="Connection closed without response" method=GET path="/socket.io/?EIO=3&transport=websocket&sid=3bKAS4OKWTP1aYl5AABP" host=chat.mondedie.fr wd="88.xxx.xxx.xxx" dyno=web.1 connect=0ms service=1ms status=503 bytes=0
```

Moimeme semble avoir eu un petit soucis réseau, le socket semble avoir été ouvert 4 fois à la suite, peut-être que ça peut expliquer que l'event soit _registered_ 4 fois aussi, je sais pas quoi en déduire. A méditer.

**Comment by hardware** [comment]
En espérant que ça fonctionne. 

Sinon @soyuka, tu connais pas un petit trick en javascript pour enregistrer un event listener qu'une et une seule fois ? Attention je parle pas d'un _one time event_ via [once](https://nodejs.org/api/events.html#events_emitter_once_event_listener) mais bien d'un événement qui peut se produire plusieurs fois dans le temps mais qui ne peut être enregistrer par le navigateur qu'une seule fois.

Normalement avec la condition :

``` javascript
if($('#clients li').length <= 0) { }
```

L'événement ne peut pas être enregistré plus d'une fois mais il existe peut-être quelque chose de plus propre, à voir.

**Comment by hardware** [comment]
Normalement le problème est corrigé je pense, je laisse ouvert quelques temps, ne pas hésiter à ajouter un commentaire si le bug se reproduit.

**Comment by soyuka** [comment]
:D

**Comment by hardware** [comment]
Bug toujours présent...

**Comment by hardware** [comment]
Bon en espérant que ça va résoudre le soucis, parce que sinon à part revoir complètement le système actuel, je vois pas comment faire.

https://github.com/socketio/socket.io-client/issues/251
https://tornadio2.readthedocs.org/en/latest/bugs/#connect-after-disconnect

http://stackoverflow.com/a/18943999
http://stackoverflow.com/a/7504015
http://stackoverflow.com/a/24574372

**Comment by Wonderfall** [comment]
Malheureusement, je viens d'avoir ce problème.
https://pix.schrodinger.io/sglXAg32/7sl2OngK.png

Cependant, on peut dire qu'il intervient plus rarement qu'avant.
