### ISSUE TITLE
Problème en cas de loadbalancing

### ISSUE THREAD

**Issue by Hydrog3n** [mondediefr/mondedie-chat#20]
Certaine personne disparaisse de la liste des utilisateurs quand ils ont une connexion avec un loadbalancing. Il y a une solution pour corriger ça de notre coté ?

**Comment by soyuka** [comment]
Vous utilisez le cluster ?
Le lun. 7 déc. 2015 à 19:18, Loïc Vaillé notifications@github.com a
écrit :

**Comment by Hydrog3n** [comment]
Non mais c'est un utilisateur qui utilise un loadballancing.

**Comment by hardware** [comment]
En fait il a plusieurs lignes ADSL mais une seule IP WAN, quand la première ligne n'est pas disponible son routeur prend la seconde tout en gardant la même IP.

Si on part sur ce principe, pendant la coupure, il perds la connexion au socket donc le serveur le retire de la liste des membres connectés, quand il a de nouveau une connexion, le navigateur réouvre le socket et normalement il doit réapparaitre en tant que membre connecté.

Le soucis c'est qu'il arrive à ouvrir plusieurs connexions en même temps apparement :

![screen](https://i.gyazo.com/5ffad32e32bcf87011215bef83326302.png)

Dans ce screen, on voit qu'il ouvre 4 sockets au chat en même temps (9:41:57), ensuite le premier se ferme à 9:42:39, donc de 9:42:39 à 9:44:05, il n'apparait pas connecté sur le chat mais il est tout de même bien présent (via les sockets qui sont pas encore déconnectés).

Le chat n'a même pas le temps de détecter l'ouverture des autres sockets puisque tout ce fait pendant la même seconde.

J'ai essayé de faire ça en local mais j'arrive pas à reproduire ce bug, je suis pas assez rapide je pense :smile: 

Le pire dans tout ça c'est qu'on a 1 chance sur 4 de ban le bon socket, je suis quasiment sûr que quand il est dans ce cas là,  on ne puisse pas à tous les coups le ban du chat, pareil pour tout ce qui dépend du socket en fait (messages privés, poke, roll...etc).

Normalement chaque membre à un socket unique qui est enregistré dans la BDD, dans ce cas, la bdd ne connait que l'ID du dernier socket ouvert et pas des 3 autres.

**Comment by soyuka** [comment]
En gros ca veut dire qu'il faut que les identifiants des sessions soient l'ip, ou du moins quelque chose d'unique que l'on retrouve grâce à l'ip. Comme ca il ne se connectera plus qu'une fois depuis l'ip de sortie et s'il se reconnecte tu renvoie le socket qui correspond, qui lui est déjà ouvert.

**Comment by hardware** [comment]
Ouais c'est pas mal comme solution, ça résoud le soucis des multiples identifiants, par contre, il reste encore le problème d'origine, il disparaitra dans tous les cas de la liste des utilisateurs connectés vu qu'il ouvre plusieurs connexions exactement à la même seconde, pour le chat il n'y a pas de socket déjà ouvert, donc il va traiter les 4 connexions en parallèle de la même manière (càd en tant que nouvelle connexion).

**Comment by soyuka** [comment]
ah bah ca c'est un bug parce qu'avec un pseudo-code du genre ca marche à tous les coups :

```
soit, Nouvel utilisateur identifié par IP
soit, ttl = 10 minutes (timeout de la session)

S'il n'y a pas de session pour l'ip dans redis
   alors je lui en créé une qui va périr dans ttl 
sinon
   je récupère la session 

J'attribue la session trouvée au client qui l'a demandée   
```

Du coup même s'il y en avait plusieurs, ca réduirai quand même le risque qu'il en créé des "fantômes".

**Comment by hardware** [comment]
Normalement le commit 9a7a03b devrait résoudre les problèmes de connexion au moins, mais faudra quand même implémenter la solution de soyuka pour ne pas se retrouver avec des sessions fantômes.
