### ISSUE TITLE
bug css word-wrap [firefox] / .section--center max-width

### ISSUE THREAD

**Issue by al3xLvs** [mondediefr/mondedie-chat#21]
![](https://lut.im/aTVCCVV6Yg/Fpgs60qLtFVgeiVz.png)
La césure pour les mots trop long ne se fait pas correctement avec firefox.

**Comment by al3xLvs** [comment]
J'ai une solution qui consiste à passer la class `.text`en `display: block;` ça règle le problème.
Mais ça implique de faire une refonte de l'affichage des messages. Puisque avec display block les messages seront en dessous du pseudo.

On peut s'inspirer de gitter ou slack pour ça peut-être. Il faudrait voir ça à la refonte de l'affichage des dates par exemple.

**Comment by hardware** [comment]
Je sais pas si c'est lié mais quand on multiplie les citations en markdown, on peut rendre le chat inutilisable comme sur ton screen.

**Comment by hardware** [comment]
Quelqu'un a une idée pour résoudre le problème de largeur au niveau de `.section--center` ?

On peut rendre le chat inutilisable qu'importe le navigateur avec ceci par exemple :

```
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > Votre citation

1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.  texte à puce ici

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - texte à puce ici
```

Le problème doit être réglé avec l'aide du CSS pas via Javascript.

@Magicalex : Tu penses que le problème peut être réglé avec `max-width` ou une directive `flex-*` équivalente ?

**Comment by al3xLvs** [comment]
tu utilises quel navigateur?

**Comment by hardware** [comment]
J'ai testé avec :

Chromium 50.0.2661.102
Firefox 46.0.1
Opera 37.0.2178.32

**Comment by al3xLvs** [comment]
j'ai une solution provisoire, je push mais je test un truc avant

**Comment by al3xLvs** [comment]
Moi perso le problème est résolu.
Mais l'inconvénient de cette solution c'est pour les personnes qui ont une grande résolution, elles seront limitées à 900px.

**Comment by hardware** [comment]
En effet c'est un peu génant :smile: 

[![](https://images.mondedie.fr/e5K27OIo/tZANwQ3A.png)](https://images.mondedie.fr/e5K27OIo/tZANwQ3A.png)

J'ai une résolution standard, 1920x1080.

EDIT : 
Mais même avec un max-width à 900px, les résolutions inférieures (tablette, smartphone) auront le problème. Faudrait une limite qui s'adapte aux proportions de l'écran. J'essaierai de regarder demain, si tu as une idée dans ce sens n'hésite pas.

**Comment by al3xLvs** [comment]
media querie pas le choix du coup. Faudra réutiliser les mixins de bootstrap.

Doc bootstrap : http://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints
Un exemple : https://github.com/mondediefr/mondedie-chat/blob/master/client/scss/_layout.scss#L126

**Comment by Moimemeici** [comment]
![chat mondedie](https://cloud.githubusercontent.com/assets/19207283/15273940/bc844778-1aa7-11e6-9ced-60b217ebdc18.PNG)

**Comment by hardware** [comment]
Le commit 061976b a fermé automatiquement l'issue, désolé.

Le problème initial a été réglé (word-wrap bug sous Firefox) mais il reste toujours l'autre soucis...

**Comment by al3xLvs** [comment]
voilà j'ai fait une proposition qui fonctionne pas trop mal.
A voir si ça crée pas trop de problème notamment avec les petites résolutions.
