### ISSUE TITLE
sh: 1: node: not found,npm WARN This failure might be due to the use of legacy binary "node"

### ISSUE THREAD

**Issue by Noktam** [mondediefr/mondedie-chat#26]
Je n'arrive pas a installer le chat en suivant la procédure d'install manuelle décrite sur le github : 

user@XXXX:~/chat/mondedie-chat# npm install -g bower gulp pm2
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.11
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
/usr/local/bin/pm2 -> /usr/local/lib/node_modules/pm2/bin/pm2
/usr/local/bin/pm2-dev -> /usr/local/lib/node_modules/pm2/bin/pm2-dev
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
gulp@3.9.1 /usr/local/lib/node_modules/gulp
âââ interpret@1.0.0
âââ pretty-hrtime@1.0.2
âââ deprecated@0.0.1
âââ archy@1.0.0
âââ tildify@1.2.0 (os-homedir@1.0.1)
âââ minimist@1.2.0
âââ v8flags@2.0.11 (user-home@1.1.1)
âââ chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
âââ semver@4.3.6
âââ orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
âââ liftoff@2.2.1 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.2, resolve@1.1.7, findup-sync@0.3.0)
âââ gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, gulplog@1.0.0, lodash.template@3.6.2, vinyl@0.5.3, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
âââ vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

pm2@1.1.2 /usr/local/lib/node_modules/pm2
âââ ikt@0.0.0
âââ eventemitter2@0.4.14
âââ pidusage@1.0.1
âââ semver@5.1.0
âââ commander@2.9.0 (graceful-readlink@1.0.1)
âââ debug@2.2.0 (ms@0.7.1)
âââ chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
âââ async@1.5.2
âââ pm2-multimeter@0.1.2 (charm@0.1.2)
âââ pm2-deploy@0.2.1 (async@1.4.2, tv4@1.0.18)
âââ pm2-axon@2.0.11 (amp-message@0.1.2, escape-regexp@0.0.1, amp@0.3.1, configurable@0.0.1)
âââ mkdirp@0.5.1 (minimist@0.0.8)
âââ pm2-axon-rpc@0.3.6 (json-stringify-safe@5.0.1, commander@1.0.5)
âââ pmx@0.6.1 (json-stringify-safe@5.0.1)
âââ cli-table@0.3.1 (colors@1.0.3)
âââ vizion@0.2.12 (async@0.9.0)
âââ nssocket@0.6.0 (lazy@1.0.11)
âââ shelljs@0.6.0
âââ coffee-script@1.10.0
âââ source-map-support@0.4.0 (source-map@0.1.32)
âââ yamljs@0.2.7 (glob@4.5.3, argparse@0.1.16)
âââ chokidar@1.4.3 (path-is-absolute@1.0.0, inherits@2.0.1, glob-parent@2.0.0, async-each@1.0.0, is-binary-path@1.0.1, is-glob@2.0.1, anymatch@1.3.0, readdirp@2.0.0)
âââ cron@1.1.0 (moment-timezone@0.3.1)
âââ moment@2.13.0

bower@1.7.9 /usr/local/lib/node_modules/bower
user@XXXX:~/chat/mondedie-chat# npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN engine gulp-autoprefixer@3.1.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine gulp-inject@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine gulp-size@2.1.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine gzip-size@3.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine postcss@5.0.19: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated jade@0.29.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
\

> spawn-sync@1.0.15 postinstall /root/chat/mondedie-chat/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/root/chat/mondedie-chat/node_modules/gulp-sass/node_modules/node-sass/node_modules/sass-graph/node_modules/lodash'
npm ERR! error rolling back  node-sass@3.4.2 { [Error: ENOTEMPTY, rmdir '/root/chat/mondedie-chat/node_modules/gulp-sass/node_modules/node-sass/node_modules/sass-graph/node_modules/lodash']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/root/chat/mondedie-chat/node_modules/gulp-sass/node_modules/node-sass/node_modules/sass-graph/node_modules/lodash' }
npm ERR! tar.unpack untar error /root/.npm/lodash/4.11.1/package.tgz
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.6-docker-6
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/chat/mondedie-chat
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! tar.unpack untar error /root/.npm/node-gyp/3.3.1/package.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/chat/mondedie-chat/npm-debug.log
npm ERR! not ok code 0

**Comment by Hydrog3n** [comment]
Salut, merci pour le retour tu pourrais nous dire ta version de nodejs ?  `node --version`

**Comment by Noktam** [comment]
Ok, j'ai compris du coup, quand on installe nodejs sur debian, l'executable c'est nodejs et pas node.
J'ai fait un link /usr/bin/nodejs /usr/bin/node et ca semble etre rentré dans l'ordre.
Par contre maintenant j'ai un autre soucis, si je lance la page web j'ai  : ENOENT, no such file or directory '/xxx/xxx/mondedie-chat/views/includes/build/javascript.jade' (et meme chose pour css.jade)

**Comment by hardware** [comment]
Il faut pas oublier de build l'application avec **gulp**

**Comment by Noktam** [comment]
Ah ok, j'avais zappé cette commande, par contre gulp me fait ca : 
/xxx/chat/mondedie-chat/mondedie-chat/node_modules/gulp-inject/src/inject/index.js:127
      startTag,
              ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/xxx/chat/mondedie-chat/mondedie-chat/node_modules/gulp-inject/index.js:4:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by soyuka** [comment]
Met ton node à jour, 0.10 c'est vieux.

**Comment by Noktam** [comment]
Et tu pense que ca va regler le probleme avec gulp ?

**Comment by hardware** [comment]
Probablement oui, personnellement je n'ai pas cette erreur pendant le build.

**Comment by Noktam** [comment]
Ok, effectivement ca a reglé le probleme. Merci !

**Comment by al3xLvs** [comment]
I'm a live (comprendra qui pourra :D )

**Comment by soyuka** [comment]
👯
