### ISSUE TITLE
Ajouter un thème sombre

### ISSUE THREAD

**Issue by hardware** [mondediefr/mondedie-chat#3]
Ajouter un bouton permettant de switcher entre 2 thèmes, un clair et un sombre.

**Comment by Hydrog3n** [comment]
Naaaan :D 
Mais faire un truc pour faire facilement des thèmes pourquoi pas.

**Comment by soyuka** [comment]
Le seul truc reloud avec les thèmes-switch c'est le css. Genre soit tu met tous les styles sur la page et après tu change l'id du conteneur ou soit du galère avec du js :p.
