### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by soyuka** [mondediefr/mondedie-chat#31]
Mouais, ca tape dans les serveurs de fb...

Cas ou sur npm y'a aussi un lock avec la commande `npm shrinkwrap`.

**Comment by hardware** [comment]
Apparement Yarn a été plutôt bien accueilli par la communauté et par les développeurs de NPM :

http://blog.npmjs.org/post/151660845210/hello-yarn

Après c'est pas obligatoire de passer par Yarn, npm reste compatible (en prod c'est toujours npm qui est utilisé sur chat.mondedie.fr). J'imagine qu'on peut changer le registry facilement, pour le moment ça pointe sur registry.yarnpkg.com

**Comment by hardware** [comment]
```
time yarn
0:28.38 elapsed
time npm install
1:23.11 elapsed
```

Niveau temps d'execution c'est mieux, je suis passé à Yarn surtout parce que le projet a l'air d'être plutôt prometteur. Mais c'est vrai qu'il vaudrait mieux utiliser le registry de npmjs.org

@Hydrog3n @Magicalex vous en pensez quoi ?

**Comment by hardware** [comment]
Je viens de changer le registry comme ceci :

```
npm config ls -l | grep registry
  registry = "https://registry.npmjs.org/"

yarn config list | grep registry
  registry: 'https://registry.yarnpkg.com',

yarn config set registry https://registry.npmjs.org
```

ça semble bien fonctionner avec celui de npmjs.org :

```
yarn

yarn install v0.16.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 30.20s.
```

**Comment by soyuka** [comment]
:) c'était juste une remarque fb étant une grosse société alors que les gars de npm sont à 80% trans et ont les cheveux colorés :noel: (ils sont genre 4)

**Comment by hardware** [comment]
aha je savais pas pour NPM xD

Perso côté open-source, j'ai rien contre facebook vu ce qu'ils font (react...etc https://github.com/facebook) mais dans l'absolu, c'est vrai qu'on peut se poser des questions sur le fonctionnement de leur registry. Je pense que ça doit être utilisé pour faire des statistiques/tests et ensuite ils forward vers npmjs.org

**Comment by soyuka** [comment]
nope a mon avis ils ont cloné le registry, tu peux te faire ton private registry sans prob ;). Perso je vais utiliser preact ou cycle.js plutôt que le react de FB juste pck c'est FB ^^.

Tu me dira j'ai quand même star yarn.

**Comment by Hydrog3n** [comment]
Les stats avec le register de npm ça va aussi vite ? 
Dans ma boite j'ai un register privé pour faire proxy de celui de npm par exemple !

**Comment by soyuka** [comment]
bah t'as bien raison pck si npm chie bah tu peux tjrs passer en prod :cat: 

Niveau stats je sais pas perso
