### ISSUE TITLE
Piwik n'est pas activé

### ISSUE THREAD

**Issue by Wonderfall** [mondediefr/mondedie-chat#35]
J'ai bien ajouté et configuré les variables `PIWIK_ID` et `PIWIK_URL` mais aucun tracking n'est activé. Je constate la même chose sur chat.mondedie.fr, mais je ne sais pas si c'est volontaire.

**Comment by hardware** [comment]
Piwik n'est actif que dans l'espace chatroom : https://github.com/mondediefr/mondedie-chat/blob/e638301073dbedc708c3f16b622ccf1eeb196631/views/includes/assets/javascript.pug#L1

Pas au niveau de la page de connexion.

**Comment by Wonderfall** [comment]
Ah je suis con... Merci de l'info.
