### ISSUE TITLE
Rendre l'interface responsive

### ISSUE THREAD

**Issue by hardware** [mondediefr/mondedie-chat#4]
Voir :

http://v4-alpha.getbootstrap.com/layout/overview/
http://v4-alpha.getbootstrap.com/layout/responsive-utilities/
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L89-L100
- [x] Bug du textarea problème avec le height sur le breakpoint xs et sm.
- [x] logo mondedie dépasse sur login et chatroom (en breakpoint sm).
- [x] Trouver une solution pour que les users puissent se déconnecter sur les devices phones. (slideout.js)
- [x] Ajouter titre (hover) pour afficher les pseudos des images.

**Comment by Magicalex** [comment]
grid-breakpoints : https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L89-L112

**Comment by Magicalex** [comment]
trouver une solution pour que les users puissent se déconnecter sur les devices phones.
