### ISSUE TITLE
Rendre les options persistante.

### ISSUE THREAD

**Issue by al3xLvs** [mondediefr/mondedie-chat#8]
A chaque fois que l'on recharge la page les options sont perdu.
Il faudrait ajouter des cookies pour conserver les réglages.

**Comment by hardware** [comment]
Ouais bonne idée, pour l'instant ce n'est pas forcément utile vu les options mais ça pourrait être utile à l'avenir

**Comment by al3xLvs** [comment]
C'est utile en ce moment je trouve, notamment sur désactiver les infos de connexion c'est pénible de cocher la case à chaque fois.
