### ISSUE TITLE
Format de la date 

### ISSUE THREAD

**Issue by al3xLvs** [mondediefr/mondedie-chat#9]
Je propose de formater la date par rapport à l'instant présent.
http://momentjs.com/docs/#/displaying/from/

il y a 1 min, c'est plus intuitif pour les discussions instantanée.
Ensuite mettre la date à coté de la croix delete?

**Comment by Hydrog3n** [comment]
Je suis d'accord. Par contre à plus de 24h on affiche la date ?

**Comment by al3xLvs** [comment]
Je sais pas trop, ouais au bout de 48h ou 24h il en pense quoi @hardware ?

**Comment by hardware** [comment]
ouais 48h ça me semble pas mal.

**Comment by al3xLvs** [comment]
Done.
https://github.com/mondediefr/mondedie-chat/commit/a1876be5e10fd981ecb4be9feefb3a0082b1a4f0
https://github.com/mondediefr/mondedie-chat/commit/938bce1c33c032b62e0623a3a5d9042b484b9f59
https://github.com/mondediefr/mondedie-chat/commit/35d345a2c9359320dca1f7d492674e074d218b50
https://github.com/mondediefr/mondedie-chat/commit/2d3bfbd04a56ee60641bf8475f0b1c2dcdd172a2
